### ISSUE TITLE
Push Privileges

### ISSUE THREAD

**Issue by ghost** [jng017/rshell#1]
Have you given the instructors the ability to push to this repository yet? I'm getting HTPP 403 errors when I attempt to grade your submission.

**Comment by levinlozenges** [comment]
Sorry, push privileges? I'm not sure what you mean. The Repository is public; am I supposed to add all the TAs and graders as collaborators to the rshell project as well?

**Comment by ghost** [comment]
Sorry, yes, when I said push privileges, I meant you need to add us as collaborators so that we can push your grades back to your repository.

**Comment by levinlozenges** [comment]
Oh, I never added you as a collaborator on my repository! I only added Busra and Professor Izbicki. sorry. I should have you on the collaborator's list on my ucr-cs100 fork now.
